[package]
name = "lua-rs"
authors = ["Haron"]
version = "0.0.1"
publish = false

[lib]
#path = "lib.rs"
crate-type = ["staticlib"]

[[bin]]
name = "lua"
path = "src/main.rs"

[dependencies]
libc = "0.2"
